[package]
name = "beluga-desktop"
version = "0.3.0"
description = "Beluga desktop app"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
beluga-core = { path = "../../../crates/beluga-core" }
beluga-spatial = { path = "../../../crates/beluga-spatial" }
beluga-audio-io = { path = "../../../crates/beluga-audio-io" }

[features]
custom-protocol = ["tauri/custom-protocol"]
